/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbastecimentosRouteImport } from './routes/abastecimentos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ViagemRouteImport } from './routes/viagem'
import { Route as HistoricoIndexRouteImport } from './routes/historico.index'
import { Route as HistoricoTripIdRouteImport } from './routes/historico.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentosRoute = AbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagemRoute = ViagemRouteImport.update({
  id: '/viagem',
  path: '/viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoTripIdRoute = HistoricoTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => HistoricoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/metodologia': typeof MetodologiaRoute
  '/relatorios': typeof RelatoriosRoute
  '/viagem': typeof ViagemRoute
  '/historico/$tripId': typeof HistoricoTripIdRoute
  '/historico/': typeof HistoricoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/metodologia': typeof MetodologiaRoute
  '/relatorios': typeof RelatoriosRoute
  '/viagem': typeof ViagemRoute
  '/historico/$tripId': typeof HistoricoTripIdRoute
  '/historico': typeof HistoricoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/metodologia': typeof MetodologiaRoute
  '/relatorios': typeof RelatoriosRoute
  '/viagem': typeof ViagemRoute
  '/historico/$tripId': typeof HistoricoTripIdRoute
  '/historico/': typeof HistoricoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimentos'
    | '/historico'
    | '/metodologia'
    | '/relatorios'
    | '/viagem'
    | '/historico/$tripId'
    | '/historico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimentos'
    | '/metodologia'
    | '/relatorios'
    | '/viagem'
    | '/historico/$tripId'
    | '/historico'
  id:
    | '__root__'
    | '/'
    | '/abastecimentos'
    | '/historico'
    | '/metodologia'
    | '/relatorios'
    | '/viagem'
    | '/historico/$tripId'
    | '/historico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentosRoute: typeof AbastecimentosRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
  MetodologiaRoute: typeof MetodologiaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ViagemRoute: typeof ViagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimentos': {
      id: '/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AbastecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagem': {
      id: '/viagem'
      path: '/viagem'
      fullPath: '/viagem'
      preLoaderRoute: typeof ViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/$tripId': {
      id: '/historico/$tripId'
      path: '/$tripId'
      fullPath: '/historico/$tripId'
      preLoaderRoute: typeof HistoricoTripIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
  }
}

interface HistoricoRouteChildren {
  HistoricoTripIdRoute: typeof HistoricoTripIdRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoTripIdRoute: HistoricoTripIdRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentosRoute: AbastecimentosRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
  MetodologiaRoute: MetodologiaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ViagemRoute: ViagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}